apiVersion: v1
kind: Service
metadata:
  name: qrust-api-service
spec:
  # 클라우드 환경에서 외부 로드 밸런서를 프로비저닝합니다.
  type: LoadBalancer
  selector:
    # 이 selector는 Deployment의 spec.template.metadata.labels와 일치해야 합니다.
    app: qrust-api
  ports:
    - protocol: TCP
      # 외부에서 로드 밸런서로 접근할 포트
      port: 80
      # 로드 밸런서가 트래픽을 전달할 컨테이너의 포트
      targetPort: 8080
